name: Update plugins.json

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v4
        
      - name: install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: run deno script
        run: deno run --allow-net=keepass.info,api.github.com,sourceforge.net --allow-write --allow-env loadPlugins.js
        env:
          GITHUB_PAT: ${{secrets.PAT}}

      - name: run versions script
        run: deno run --allow-net=keepass.info,api.github.com,sourceforge.net --allow-write --allow-env loadVersions.js
        env:
          GITHUB_PAT: ${{secrets.PAT}}

      - name: commit and push
        run: |
          git config --global user.email "cesar.bernard@gmx.de"
          git config --global user.name "CennoxX"
          git config --global credential.helper cache
          git clone https://${{secrets.PAT}}@github.com/${GITHUB_REPOSITORY}
          cp plugins.json  plugin_tests/plugins.json
          cp mirroredVersion.info  plugin_tests/mirroredVersion.info
          cp allVersion.info  plugin_tests/allVersion.info
          cd plugin_tests
          git add allVersion.info
          git add plugins.json
          git add mirroredVersion.info
          git commit -m "Update plugins [skip ci]" || false
          git push || false
