name: Update plugins.json

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v4
        
      - name: install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: run deno script
        run: deno run --allow-net=keepass.info --allow-write loadPlugins.js

      - name: Check for changes
        id: check_diff
        run: |
          git diff --exit-code plugins.json && exit 0 || echo "Changes detected"

      - name: commit and push
        run: |
          git config --global user.email "cesar.bernard@gmx.de"
          git config --global user.name "CennoxX"
          git config --global credential.helper cache
          git clone https://${{secrets.PAT}}@github.com/${GITHUB_REPOSITORY}
          cp plugins.json plugin_tests/plugins.json
          cd plugin_tests
          git add plugins.json
          git commit -m "Update plugins.json [skip ci]"
          git push
